before_script:
  - apt-get update && apt-get -y install make curl gnupg2

stages:
  - lint
  - test
  - build

web-frontend-eslint:
  stage: lint
  image: node:12
  script:
    - cd web-frontend
    - make install-dependencies
    - make eslint

web-frontend-stylelint:
  stage: lint
  image: node:12
  script:
    - cd web-frontend
    - make install-dependencies
    - make stylelint

web-frontend-test:
  stage: test
  image: node:12
  script:
    - cd web-frontend
    - make install-dependencies
    - make test

backend-flake8:
  stage: lint
  image: python:3.7
  script:
    - cd backend
    - make install-dependencies
    - make install-dev-dependencies
    - make lint

backend-pytest:
  stage: test
  image: python:3.7
  services:
    - name: postgres:11.3
      alias: db
    - name: liminspace/mjml-tcpserver:0.10
      alias: mjml
  variables:
    POSTGRES_USER: baserow
    POSTGRES_PASSWORD: baserow
    POSTGRES_DB: baserow
  script:
    - cd backend
    - make install-dependencies
    - make install-dev-dependencies
    - export PYTHONPATH=$CI_PROJECT_DIR/backend/src:$CI_PROJECT_DIR/premium/backend/src
    - make test-parallel

backend-setup:
  stage: build
  image: python:3.7
  script:
    - pip install -e ./backend
    - python -c 'import baserow'
    - pip install -e ./premium/backend
    - python -c 'import baserow_premium'
    - export DJANGO_SETTINGS_MODULE='baserow.config.settings.base'
    - timeout --preserve-status 10s gunicorn --workers=1 -b 0.0.0.0:8000 -k uvicorn.workers.UvicornWorker baserow.config.asgi:application
