FROM python:3.7

ADD ./backend /backend
ADD ./premium/backend /backend/plugins/premium

WORKDIR /backend

ENV PYTHONPATH $PYTHONPATH:/backend/src:/backend/plugins/premium/src
ENV DJANGO_SETTINGS_MODULE='baserow.config.settings.dev'

RUN apt-get update
RUN apt-get -y install make
RUN apt-get -y install curl
RUN apt-get -y install gnupg2

RUN make install-dependencies
RUN make install-dev-dependencies

CMD tail -f /dev/null
