FROM node:10

ADD ./web-frontend /web-frontend
ADD ./premium/web-frontend /web-frontend/plugins/premium

WORKDIR /web-frontend

RUN apt-get update
RUN apt-get -y install make
RUN apt-get -y install curl
RUN apt-get -y install gnupg2

CMD tail -f /dev/null
