# Generated by Django 2.2.11 on 2021-05-04 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0029_phonenumberfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(choices=[('ready', 'ready'), ('exporting', 'exporting'), ('complete', 'complete'), ('failed', 'failed')])),
                ('type', models.TextField(choices=[('ready', 'ready'), ('exporting', 'exporting'), ('complete', 'complete'), ('failed', 'failed')])),
                ('download_url', models.URLField(blank=True, null=True)),
                ('error', models.TextField(blank=True, choices=[('EXAMPLE_ERROR', 'EXAMPLE_ERROR')], null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.View')),
            ],
        ),
        migrations.AddIndex(
            model_name='exportjob',
            index=models.Index(fields=['user', 'view', 'type'], name='database_ex_user_id_e29c41_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='exportjob',
            unique_together={('user',), ('type',), ('view',)},
        ),
    ]
