# Generated by Django 3.2.6 on 2021-09-07 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0037_alter_exportjob_export_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormulaField",
            fields=[
                (
                    "field_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="database.field",
                    ),
                ),
                (
                    "date_format",
                    models.CharField(
                        choices=[
                            ("EU", "European (D/M/Y)"),
                            ("US", "US (M/D/Y)"),
                            ("ISO", "ISO (Y-M-D)"),
                        ],
                        default="EU",
                        help_text="EU (20/02/2020), US (02/20/2020) or ISO (2020-02-20)",
                        max_length=32,
                    ),
                ),
                (
                    "date_include_time",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the field also includes a time.",
                    ),
                ),
                (
                    "date_time_format",
                    models.CharField(
                        choices=[("24", "24 hour"), ("12", "12 hour")],
                        default="24",
                        help_text="24 (14:30) or 12 (02:30 PM)",
                        max_length=32,
                    ),
                ),
                ("formula", models.TextField()),
                ("error", models.TextField(blank=True, null=True)),
                (
                    "field_type",
                    models.TextField(
                        choices=[
                            ("text", "text"),
                            ("numeric", "numeric"),
                            ("datetime", "datetime"),
                        ],
                        default="text",
                    ),
                ),
                (
                    "number_type",
                    models.CharField(
                        choices=[("INTEGER", "Integer"), ("DECIMAL", "Decimal")],
                        default="INTEGER",
                        max_length=32,
                    ),
                ),
                (
                    "number_decimal_places",
                    models.IntegerField(
                        choices=[
                            (1, "1.0"),
                            (2, "1.00"),
                            (3, "1.000"),
                            (4, "1.0000"),
                            (5, "1.00000"),
                        ],
                        default=1,
                        help_text="The amount of digits allowed after the point.",
                    ),
                ),
                (
                    "number_negative",
                    models.BooleanField(
                        default=True,
                        help_text="Indicates if negative values are allowed.",
                    ),
                ),
                (
                    "text_default",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="If set, this value is going to be added every time a new row created.",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("database.field", models.Model),
        ),
    ]
