# Generated by Django 3.2.6 on 2021-09-01 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0037_alter_exportjob_export_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormulaField",
            fields=[
                (
                    "field_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="database.field",
                    ),
                ),
                ("formula", models.TextField()),
                ("error", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("database.field",),
        ),
    ]
