# Generated by Django 3.2.6 on 2021-09-15 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0037_alter_exportjob_export_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormulaField",
            fields=[
                (
                    "field_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="database.field",
                    ),
                ),
                ("formula", models.TextField()),
                ("error", models.TextField(blank=True, null=True)),
                (
                    "formula_type",
                    models.TextField(
                        choices=[
                            ("invalid", "invalid"),
                            ("text", "text"),
                            ("boolean", "boolean"),
                            ("date", "date"),
                            ("number", "number"),
                        ],
                        default="invalid",
                    ),
                ),
                (
                    "number_decimal_places",
                    models.IntegerField(
                        choices=[
                            (0, "1"),
                            (1, "1.0"),
                            (2, "1.00"),
                            (3, "1.000"),
                            (4, "1.0000"),
                            (5, "1.00000"),
                        ],
                        default=None,
                        help_text="The amount of digits allowed after the point.",
                        null=True,
                    ),
                ),
                (
                    "date_format",
                    models.CharField(
                        choices=[
                            ("EU", "European (D/M/Y)"),
                            ("US", "US (M/D/Y)"),
                            ("ISO", "ISO (Y-M-D)"),
                        ],
                        default=None,
                        help_text="EU (20/02/2020), US (02/20/2020) or ISO (2020-02-20)",
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "date_include_time",
                    models.BooleanField(
                        default=None,
                        help_text="Indicates if the field also includes a time.",
                        null=True,
                    ),
                ),
                (
                    "date_time_format",
                    models.CharField(
                        choices=[("24", "24 hour"), ("12", "12 hour")],
                        default=None,
                        help_text="24 (14:30) or 12 (02:30 PM)",
                        max_length=32,
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("database.field",),
        ),
        migrations.RunSQL(
            (
                """
create or replace function try_cast_to_numeric(
    p_in text
)
    returns numeric(55, 5)
as
$$
begin
    begin
        return p_in::numeric(55, 5);
    exception when others then
        return 'NaN';
    end;
end;
$$
    language plpgsql;
"""
            ),
            ("DROP FUNCTION IF EXISTS try_cast_to_numeric(text);"),
        ),
    ]
