# Generated by Django 3.2.6 on 2021-11-04 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0039_formulafield"),
    ]

    operations = [
        migrations.CreateModel(
            name="TableWebhook",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("table_id", models.IntegerField()),
                ("active", models.BooleanField(default=True)),
                ("use_user_field_names", models.BooleanField(default=True)),
                ("url", models.URLField()),
                (
                    "request_method",
                    models.CharField(
                        choices=[
                            ("POST", "Post"),
                            ("GET", "Get"),
                            ("PUT", "Put"),
                            ("PATCH", "Patch"),
                            ("DELETE", "Delete"),
                        ],
                        default="POST",
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("include_all_events", models.BooleanField(default=True)),
                ("failed_triggers", models.IntegerField(default=0)),
            ],
            options={
                "unique_together": {("table_id", "url", "request_method")},
            },
        ),
        migrations.CreateModel(
            name="TableWebhookHeader",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("header", models.TextField()),
                ("value", models.TextField()),
                (
                    "webhook_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="headers",
                        to="database.tablewebhook",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TableWebhookEvents",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("event_type", models.CharField(max_length=50)),
                (
                    "webhook_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="database.tablewebhook",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TableWebhookCall",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.UUIDField()),
                ("event_type", models.CharField(max_length=50)),
                ("called_time", models.DateTimeField(auto_now_add=True)),
                ("called_url", models.URLField()),
                ("status_code", models.IntegerField()),
                ("request", models.TextField(null=True)),
                ("response", models.TextField(null=True)),
                (
                    "webhook_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calls",
                        to="database.tablewebhook",
                    ),
                ),
            ],
        ),
    ]
