# Generated by Django 3.2.6 on 2021-11-01 09:38
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0041_field_dependencies"),
    ]

    operations = [
        # We have to split these into a separate migration and hence transaction in
        # postgres, see https://stackoverflow.com/questions/12838111/django-db
        # -migrations-cannot-alter-table-because-it-has-pending-trigger-events
        migrations.AlterField(
            model_name="formulafield",
            name="internal_formula",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="formulafield",
            name="requires_refresh_after_insert",
            field=models.BooleanField(),
        ),
    ]
