# Generated by Django 3.2.6 on 2021-11-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0043_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='trashed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='table',
            name='trashed',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
